/* eslint-disable */
export const IMPORT_DATA = 'IMPORT_DATA';
export const EXPORT_DATA = 'EXPORT_DATA';

export const APPEND_TEXT_CONTENT = 'APPEND_TEXT_CONTENT';
export const DELETE_TEXT_CONTENT = 'DELETE_TEXT_CONTENT';
export const UPDATE_TEXT_CONTENT = 'UPDATE_TEXT_CONTENT';
export const SEARCH_TEXT_CONTENT = 'SEARCH_TEXT_CONTENT';

export const APPEND_IMAGE_CONTENT = 'APPEND_IMAGE_CONTENT';
export const DELETE_IMAGE_CONTENT = 'DELETE_IMAGE_CONTENT';
export const UPDATE_IMAGE_CONTENT = 'UPDATE_IMAGE_CONTENT';
export const SEARCH_IMAGE_CONTENT = 'SEARCH_IMAGE_CONTENT';

export const CHANGE_STAR_STATUS = 'CHANGE_STAR_STATUS';
