/* eslint-disable */
// export const DECREMENT_MAIN_COUNTER = 'DECREMENT_MAIN_COUNTER'
// export const INCREMENT_MAIN_COUNTER = 'INCREMENT_MAIN_COUNTER'
export const APPEND_TEXT_CONTENT = 'APPEND_TEXT_CONTENT';
export const DELETE_TEXT_CONTENT = 'DELETE_TEXT_CONTENT';
export const UPDATE_TEXT_CONTENT = 'UPDATE_TEXT_CONTENT';
export const SEARCH_TEXT_CONTENT = 'SEARCH_TEXT_CONTENT';

export const CHANGE_STAR_STATUS = 'CHANGE_STAR_STATUS';
