###
# Clipaste Global Settings
# Time: 2017-02-26 17:22

# General
GENERAL:
  MAX_SIZE: 5
  SYNC: false
  SOUNDS: false

# Shortcuts
SHORTCUTS:
  SHOW_CLIPBOARD: CmdOrCtrl+Shift+V

# Blacklist
BLACKLIST:
